main.plugins.display-password.enabled = true
main.plugins.display-password.orientation = "horizontal"
main.plugins.display-password.position = "30,160"
main.plugins.display-password.last_only = false
